# Generated by Django 4.0.6 on 2022-12-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
